<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_flaticon-magnifying-glass2</name>
   <tag></tag>
   <elementGuidId>662cfe65-a1ce-49e5-b8dc-c37bc5f86015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[2]/div/form/div/div/div[4]/div/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/div/div[2]/div/span[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon-magnifying-glass2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/div/div[2]/div/div[2]/div/form/div/div/div[4]/div/div/div/div/div[2]/div/div/div[1]/div[1]/div/div/div/div[2]/div/span[1]/i</value>
   </webElementProperties>
</WebElementEntity>
