<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_AUTOMATION_CHART_VIEW01</name>
   <tag></tag>
   <elementGuidId>9a332475-0645-4abf-8be6-385cec98c257</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widgetid</name>
      <type>Main</type>
      <value>AUTOMATION_CHART_APP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>portlet-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-title AUTOMATION_CHART_APP_portletTitle ct-app__title ct-app__title-tm pull-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUTOMATION_CHART_VIEW01</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_0&quot;)/div[@class=&quot;panel panel-default AUTOMATION_CHART_APP ct-app ct-app-tm&quot;]/div[@class=&quot;panel-heading AUTOMATION_CHART_APP ct-app__header ct-app__header-tm ct-app__panel-header-bg&quot;]/div[@class=&quot;ct-app__header-container&quot;]/div[@class=&quot;pull-left&quot;]/h3[@class=&quot;panel-title AUTOMATION_CHART_APP_portletTitle ct-app__title ct-app__title-tm pull-left&quot;]</value>
   </webElementProperties>
</WebElementEntity>
