<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InitSubmit</name>
   <tag></tag>
   <elementGuidId>1d1f01a5-d342-49f5-8929-0318c4ba23cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//a[@data-item-id='REQ_MODEL_INIT|SUBMIT']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
