<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomineeminor</name>
   <tag></tag>
   <elementGuidId>fb74f021-7893-41c6-b995-59ff4e76f36e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//input[@id='AUTO_REQMOD01_FORM-IS_NOMINEE_MINOR']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
