<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NomineeSSN</name>
   <tag></tag>
   <elementGuidId>103b818e-b5c8-4fb2-95e0-59fbca6e35d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//input[@id='AUTO_REQMOD01_FORM-SSN']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
