<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>26862106-e7bf-4335-87de-0f7f9e9e552f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//input[@id='AUTO_REQMOD01_FORM-PASSWORD']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
