<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PAYMENT_WS</name>
   <tag></tag>
   <elementGuidId>2bfdfa5b-eeab-4f79-9764-41c3460d5082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[1]/table/tbody/tr[3]/td[3]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'PAYMENT_WS' or . = 'PAYMENT_WS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAYMENT_WS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[1]/div[@class=&quot;panel panel-default WGT_WORKSPACE_LOOKUP ct-app ct-app-tm&quot;]/div[@class=&quot;row panel-body  WGT_WORKSPACE_LOOKUP ct-app__content&quot;]/div[@class=&quot;col-md-12 panel-body  WGT_WORKSPACE_LOOKUP ct-app__content&quot;]/div[@class=&quot;col-md-12 yscroll-wrapper-container&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12 yscroll-wrapper-container&quot;]/div[@class=&quot;table-wrapper-container&quot;]/table[@class=&quot;table table-striped table-hover no-margin ct-listview ct-listview-tm&quot;]/tbody[@class=&quot;ct_pagingBody&quot;]/tr[3]/td[3]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
