<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Child App</name>
   <tag></tag>
   <elementGuidId>b163e93f-8f89-4d4e-9321-e3d5ed0a0cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='FRM_CREATE_LAYOUT-BTN_ADD_LAYOUT_APP']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input-group']//button[@id='FRM_CREATE_LAYOUT-BTN_ADD_LAYOUT_APP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FRM_CREATE_LAYOUT-BTN_ADD_LAYOUT_APP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ct_btn ct-form__ip ct-form__ip-button  ct-form__btn-composite  BTN_ADD_LAYOUT_APP_btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BTN_ADD_LAYOUT_APP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Child App </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input-group']//button[@id='FRM_CREATE_LAYOUT-BTN_ADD_LAYOUT_APP']</value>
   </webElementProperties>
</WebElementEntity>
