<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-text</name>
   <tag></tag>
   <elementGuidId>f4bd8a3a-1fcc-421b-9f9c-fd5ea541192e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='inner-field']//input[@class='input-text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ribbon&quot;)/div[@class=&quot;ribbon-ui&quot;]/div[@class=&quot;tab-data prmtab active&quot;]/div[@class=&quot;grp col-md-3&quot;]/div[@class=&quot;grp col-md-6 btns-begin inner&quot;]/span[@id=&quot;1&quot;]/div[@class=&quot;inner-field&quot;]/input[@class=&quot;input-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
