<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TEST_AUTOMATION_CONN</name>
   <tag></tag>
   <elementGuidId>6c022b8f-3bb3-4c8d-ad5c-3643367b24e9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-data</name>
      <type>Main</type>
      <value>CONNECTION_NAME|0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col-index</name>
      <type>Main</type>
      <value>CONNECTION_NAME|0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>CONNECTION_NAME</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
               TEST_AUTOMATION_CONN
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_0&quot;)/div[@class=&quot;panel panel-default WGT_CONNECTIONAPP ct-app ct-app-tm&quot;]/div[@class=&quot;row panel-body  WGT_CONNECTIONAPP ct-app__content&quot;]/div[@class=&quot;col-md-12 panel-body  WGT_CONNECTIONAPP ct-app__content&quot;]/div[@class=&quot;col-md-12 yscroll-wrapper-container&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12 yscroll-wrapper-container&quot;]/div[@class=&quot;table-wrapper-container&quot;]/table[@class=&quot;table table-striped table-hover no-margin ct-listview ct-listview-tm&quot;]/tbody[@class=&quot;ct_pagingBody&quot;]/tr[1]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
