<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_function_INIT</name>
   <tag></tag>
   <elementGuidId>bbc42433-2047-4b33-aa1c-cbed63c40b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='REQ_ENTITLEMENT_FRM-REQ_FUNCTION']//option[contains(text(),'INIT')]

//div[@class='col-lg-12 col-md-12 col-sm-12 col-xs-12']//div[@class='input-group']//select[@id='REQ_ENTITLEMENT_FRM-REQ_FUNCTION']//option[@value='INIT']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_FUNCTION'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>REQ_ENTITLEMENT_FRM-REQ_FUNCTION</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control ct-form__ip ct-form__ip-combo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>REQ_FUNCTION</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 
								APPROVE
								INIT
								VIEW
								VSBLTY
							</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_FUNCTION'])[1]</value>
   </webElementProperties>
</WebElementEntity>
