<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_SP_view</name>
   <tag></tag>
   <elementGuidId>c7d498c6-e62b-4051-b8d9-fb4beb77f694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[@id='REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT' and @name = 'REQ_SUB_PRODUCT' and (text() = '
                                Select 
								CUSER
							' or . = '
                                Select 
								CUSER
							')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control ct-form__ip ct-form__ip-combo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>REQ_SUB_PRODUCT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Select 
								CUSER
							</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[@class=&quot;panel panel-default ct-app ct-app-tm&quot;]/div[@class=&quot;panel-body ct-model__panel-body ct-app__content&quot;]/div[@class=&quot;form-wrapper&quot;]/form[@class=&quot;ct-form ct-form-tm&quot;]/div[@class=&quot;lazzyFormPanel&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-ENTITLEMENT_FLDST&quot;]/div[@class=&quot;panel panel-default ct-form__fieldset&quot;]/div[@class=&quot;panel-collapse collapse in ENTITLEMENT_FLDST&quot;]/div[@class=&quot;panel-body ct-form__fieldset_align&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-REQ_ENTITLEMENT_FRM&quot;]/div[@class=&quot;lazzyFormPanel row&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-REQ_ENTL_COMP_FLD&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ct-form-composite__row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/form[@class=&quot;form-inline ct-from__composite&quot;]/div[@class=&quot;ct-composite-REQ_SUB_PRODUCT ct-form__composite-col&quot;]/div[@class=&quot;ct-form__group ct-form__group-tm ct-cbx-combobox-bs REQ_SUB_PRODUCT-bs&quot;]/div[@class=&quot;input-group&quot;]/select[@id=&quot;REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT&quot;]</value>
   </webElementProperties>
</WebElementEntity>
