<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_search_button</name>
   <tag></tag>
   <elementGuidId>1e7a8c94-7758-4953-bad2-ac9aeb24f0e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//button[@data-action='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
