<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkspaceMenuSavebutton</name>
   <tag></tag>
   <elementGuidId>64e949e5-8607-49e3-a366-47f0467ded1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//a[@data-item-id='SAVE']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
