<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>func_category_initiate</name>
   <tag></tag>
   <elementGuidId>55d84689-bdc5-40e4-9eec-71a4e94d7052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_FUNCTION_CATEGORY'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
