<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_code_initiate</name>
   <tag></tag>
   <elementGuidId>ae3ccea8-e14f-44e0-bdc6-75721f55d890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_PRODUCT'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
