<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GCIF</name>
   <tag></tag>
   <elementGuidId>e6344eb6-a9a3-4f79-9ef6-851dee3b4e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='REQ_DATA_TABLE_DETAILS-TABLE_GCIF_COLUMN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
