<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subprdt_initiate</name>
   <tag></tag>
   <elementGuidId>23be2aa6-ed3b-4b73-906e-185d1d8b249c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
