<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subprdt_code_enquiry</name>
   <tag></tag>
   <elementGuidId>9c49b7ab-5698-4c85-a4e3-cf6560c8ae5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='REQ_ENTITLEMENT_FRM-REQ_SUB_PRODUCT'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
