<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>transaction_amt_field</name>
   <tag></tag>
   <elementGuidId>bdbb63c8-6dfc-4899-9dc5-cc863911c26e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='REQ_DATA_TABLE_DETAILS-TABLE_TXN_AMOUNT_COL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
