<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_flaticon-magnifying-glass2</name>
   <tag></tag>
   <elementGuidId>f69443b3-2637-463d-90a1-f87fd5ac26d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='form-group ct-form__group ct-form__group-tm   ct-cbx-editablelookup-bs FORM_DATA_SRC_ID-bs ']//i[@class='flaticon-magnifying-glass2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[2]/div/div/div[2]/div/div[2]/div/form/div/div/div[5]/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/div/span[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon-magnifying-glass2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div/form/div/div/div[5]/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/div/span[1]/i</value>
   </webElementProperties>
</WebElementEntity>
