<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>default_instruction_Y</name>
   <tag></tag>
   <elementGuidId>67fde8f3-25ce-4dfa-897e-7e69d8c6e903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='CREATE_VIEW_DEFINITION-INSTRUCTION_CLASS_ENABLER-0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
