<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proceed</name>
   <tag></tag>
   <elementGuidId>f907ac86-5384-41a1-8c83-1c5d2a74dd66</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btntxtcmn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max wsdesigner-mainbndl in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[@class=&quot;container-fluid ws-fullcntnt-bundle&quot;]/div[@class=&quot;ws-designer-bundle&quot;]/div[@class=&quot;ws-settings-bundle&quot;]/div[@class=&quot;ws-settings-section&quot;]/div[1]/div[@class=&quot;sdbar-btnsbndl&quot;]/button[@class=&quot;save-wsbtn wsbtnsstyl animhover&quot;]/span[@class=&quot;btntxtcmn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
