<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_flaticon-magnifying-glass2</name>
   <tag></tag>
   <elementGuidId>0130cdd3-2591-4196-a07a-ad6b5e19549c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon-magnifying-glass2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[@class=&quot;panel panel-default ct-app ct-app-tm&quot;]/div[@class=&quot;panel-body ct-model__panel-body ct-app__content&quot;]/div[@class=&quot;form-wrapper&quot;]/form[@class=&quot;ct-form ct-form-tm&quot;]/div[@class=&quot;lazzyFormPanel&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-PANEL_ITEM1&quot;]/div[@class=&quot;lazzyFormPanel&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-6 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-REQ_CONN show&quot;]/div[@class=&quot;form-group ct-form__group ct-form__group-tm   ct-cbx-editablelookup-bs REQ_CONN-bs&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon ct-editlkp&quot;]/i[@class=&quot;flaticon-magnifying-glass2&quot;]</value>
   </webElementProperties>
</WebElementEntity>
