<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TABLE_SUMMARY_COLS</name>
   <tag></tag>
   <elementGuidId>5795aec7-40b9-4c90-bbc1-0aadd1d3c073</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TABLE_SUMMARY_COLS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ct-form__ip ct-form__ip-itemselector</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[@class=&quot;panel panel-default ct-app ct-app-tm&quot;]/div[@class=&quot;panel-body ct-model__panel-body ct-app__content&quot;]/div[@class=&quot;form-wrapper&quot;]/form[@class=&quot;ct-form ct-form-tm&quot;]/div[@class=&quot;lazzyFormPanel&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-TABLE_SUMMARY_COLS&quot;]/div[@class=&quot;form-group ct-form__group ct-form__group-tm  ct-cbx-itemselector-bs TABLE_SUMMARY_COLS-bs&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12 col-lg-12&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control ct-form__ip ct-form__ip-itemselector&quot;]</value>
   </webElementProperties>
</WebElementEntity>
