<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OD_MESSAGE</name>
   <tag></tag>
   <elementGuidId>2a731a44-dd3a-4095-b1f5-a4751fbccc5b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>OD_MESSAGE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OD_MESSAGE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade  ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[1]/div[@class=&quot;panel panel-default TABLE_SELECTION_APP ct-app ct-app-tm&quot;]/div[@class=&quot;row panel-body  TABLE_SELECTION_APP ct-app__content&quot;]/div[@class=&quot;col-md-12 panel-body  TABLE_SELECTION_APP ct-app__content&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 table-responsive pull-left ct-list-table-action-padding yscroll-wrapper-container&quot;]/table[@class=&quot;table  table-striped table-hover no-margin ct-listview ct-listview-tm&quot;]/tbody[1]/tr[134]/td[2]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
