<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AUTO_CHART_VIEW01</name>
   <tag></tag>
   <elementGuidId>7b01bf23-335b-41dc-b8ed-a7f8a5541d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='LIST_VIEW_DEFN_LOOKUP']//td[@data-item-data='VIEW_ID|0']//span[contains(text(),'AUTOMATION_CHART_VIEW01')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'AUTO_CHART_VIEW01' or . = 'AUTO_CHART_VIEW01')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUTO_CHART_VIEW01</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[1]/div[@class=&quot;panel panel-default WGT_VIEWDEFNLOOKUP ct-app ct-app-tm&quot;]/div[@class=&quot;row panel-body  WGT_VIEWDEFNLOOKUP ct-app__content&quot;]/div[@class=&quot;col-md-12 panel-body  WGT_VIEWDEFNLOOKUP ct-app__content&quot;]/div[@class=&quot;col-md-12 yscroll-wrapper-container&quot;]/div[@class=&quot;col-sm-12 col-xs-12 col-lg-12 yscroll-wrapper-container&quot;]/div[@class=&quot;table-wrapper-container&quot;]/table[@class=&quot;table table-striped table-hover no-margin ct-listview ct-listview-tm&quot;]/tbody[@class=&quot;ct_pagingBody&quot;]/tr[1]/td[@class=&quot;highlight-class&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
