<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_More2</name>
   <tag></tag>
   <elementGuidId>7acb2c54-783c-4d7d-b451-99539bae040d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-item-id='VIEW_ITEMS_MULTI_FORM_2']//div[@class='input-group']//button[@id='VIEW_ITEMS_MULTI_FORM-BTN_ADD_MORE']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'VIEW_ITEMS_MULTI_FORM-BTN_ADD_MORE' and @type = 'button' and @name = 'BTN_ADD_MORE' and (text() = 'More' or . = 'More')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VIEW_ITEMS_MULTI_FORM-BTN_ADD_MORE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ct_btn ct-form__ip ct-form__ip-button  ct-form__btn-composite  BTN_ADD_MORE_btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BTN_ADD_MORE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FOOTER_DIV&quot;)/div[@class=&quot;modal fade modal-fullscreen force-fullscreen ct-modal ct-modal__max in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ct-modal-content__container&quot;]/div[@class=&quot;panel panel-default ct-app ct-app-tm&quot;]/div[@class=&quot;panel-body ct-model__panel-body ct-app__content&quot;]/div[@class=&quot;form-wrapper&quot;]/form[@class=&quot;ct-form ct-form-tm&quot;]/div[@class=&quot;lazzyFormPanel&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-VIEW_ITEMS_SET show&quot;]/div[@class=&quot;panel panel-default ct-form__fieldset&quot;]/div[@class=&quot;panel-collapse collapse in VIEW_ITEMS_SET&quot;]/div[@class=&quot;panel-body ct-form__fieldset_align&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-VIEW_ITEMS_MULTI_FORM&quot;]/div[@class=&quot;lazzyFormPanel row&quot;]/div[@class=&quot;formcontainer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 data-width&quot;]/div[@class=&quot;ct-form__anchor-width&quot;]/div[@class=&quot;ct-formlayout-VIEW_ITEMS_COMP&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ct-form-composite__row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/form[@class=&quot;form-inline ct-from__composite&quot;]/div[@class=&quot;ct-composite-BTN_ADD_MORE ct-form__composite-col&quot;]/di[@class=&quot;form-group ct-form__group ct-form__group-tm   ct-cbx-button-bs BTN_ADD_MORE-bs&quot;]/div[@class=&quot;input-group&quot;]/button[@id=&quot;VIEW_ITEMS_MULTI_FORM-BTN_ADD_MORE&quot;]</value>
   </webElementProperties>
</WebElementEntity>
